services:
  - type: web
    name: linkedin-scraper-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    # Add your environment variables here in Render dashboard
